version: "3.4"
services:
  fast-backend_debug:
    build:
      context: .
      dockerfile: "Dockerfile"
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    entrypoint: "/start-reload.sh"
    environment:
      DB_HOST: "localhost"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "1234"
      DB_NAME: "fast"
      DB_PORT: 15432
    