version: "3.4"
services:
  fast-backend_debug:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "8000:80"
    entrypoint: "/start-reload.sh"
    environment:
      DB_HOST: "host.docker.internal"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "1234"
      DB_NAME: "fast"
      DB_PORT: 15432
    