version: "3.4"
services:
  fast-backend:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "8000:80"
    environment:
      ACCESS_LOG: "/app/log/gunicorn.access.log"
      ERROR_LOG: "/app/log/gunicorn.error.log"
      LOG_LEVEL: "info"
      DB_HOST: "172.17.0.1"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "1234"
      DB_NAME: "fast"
      DB_PORT: 15432
    